/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedStudiosVideoEditorRouteImport } from './routes/_authenticated.studios.video-editor'
import { Route as AuthenticatedStudiosPhotoRouteImport } from './routes/_authenticated.studios.photo'
import { Route as AuthenticatedStudiosCartoonRouteImport } from './routes/_authenticated.studios.cartoon'
import { Route as AuthenticatedStudiosAnimeRouteImport } from './routes/_authenticated.studios.anime'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudiosVideoEditorRoute =
  AuthenticatedStudiosVideoEditorRouteImport.update({
    id: '/studios/video-editor',
    path: '/studios/video-editor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudiosPhotoRoute =
  AuthenticatedStudiosPhotoRouteImport.update({
    id: '/studios/photo',
    path: '/studios/photo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudiosCartoonRoute =
  AuthenticatedStudiosCartoonRouteImport.update({
    id: '/studios/cartoon',
    path: '/studios/cartoon',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudiosAnimeRoute =
  AuthenticatedStudiosAnimeRouteImport.update({
    id: '/studios/anime',
    path: '/studios/anime',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/studios/anime': typeof AuthenticatedStudiosAnimeRoute
  '/studios/cartoon': typeof AuthenticatedStudiosCartoonRoute
  '/studios/photo': typeof AuthenticatedStudiosPhotoRoute
  '/studios/video-editor': typeof AuthenticatedStudiosVideoEditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/studios/anime': typeof AuthenticatedStudiosAnimeRoute
  '/studios/cartoon': typeof AuthenticatedStudiosCartoonRoute
  '/studios/photo': typeof AuthenticatedStudiosPhotoRoute
  '/studios/video-editor': typeof AuthenticatedStudiosVideoEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/studios/anime': typeof AuthenticatedStudiosAnimeRoute
  '/_authenticated/studios/cartoon': typeof AuthenticatedStudiosCartoonRoute
  '/_authenticated/studios/photo': typeof AuthenticatedStudiosPhotoRoute
  '/_authenticated/studios/video-editor': typeof AuthenticatedStudiosVideoEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/studios/anime'
    | '/studios/cartoon'
    | '/studios/photo'
    | '/studios/video-editor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/dashboard'
    | '/studios/anime'
    | '/studios/cartoon'
    | '/studios/photo'
    | '/studios/video-editor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/privacy'
    | '/terms'
    | '/_authenticated/dashboard'
    | '/_authenticated/studios/anime'
    | '/_authenticated/studios/cartoon'
    | '/_authenticated/studios/photo'
    | '/_authenticated/studios/video-editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studios/video-editor': {
      id: '/_authenticated/studios/video-editor'
      path: '/studios/video-editor'
      fullPath: '/studios/video-editor'
      preLoaderRoute: typeof AuthenticatedStudiosVideoEditorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studios/photo': {
      id: '/_authenticated/studios/photo'
      path: '/studios/photo'
      fullPath: '/studios/photo'
      preLoaderRoute: typeof AuthenticatedStudiosPhotoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studios/cartoon': {
      id: '/_authenticated/studios/cartoon'
      path: '/studios/cartoon'
      fullPath: '/studios/cartoon'
      preLoaderRoute: typeof AuthenticatedStudiosCartoonRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studios/anime': {
      id: '/_authenticated/studios/anime'
      path: '/studios/anime'
      fullPath: '/studios/anime'
      preLoaderRoute: typeof AuthenticatedStudiosAnimeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedStudiosAnimeRoute: typeof AuthenticatedStudiosAnimeRoute
  AuthenticatedStudiosCartoonRoute: typeof AuthenticatedStudiosCartoonRoute
  AuthenticatedStudiosPhotoRoute: typeof AuthenticatedStudiosPhotoRoute
  AuthenticatedStudiosVideoEditorRoute: typeof AuthenticatedStudiosVideoEditorRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedStudiosAnimeRoute: AuthenticatedStudiosAnimeRoute,
  AuthenticatedStudiosCartoonRoute: AuthenticatedStudiosCartoonRoute,
  AuthenticatedStudiosPhotoRoute: AuthenticatedStudiosPhotoRoute,
  AuthenticatedStudiosVideoEditorRoute: AuthenticatedStudiosVideoEditorRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
